apiVersion: v1
kind: Secret
metadata:
  name: oncall-shift-reporter
  namespace: oncall-shift-reporter
type: Opaque
data:
  PAGERDUTY_AUTH_TOKEN: {{ .Values.pagerduty.auth_token }}
  SLACK_KEY: {{ .Values.slack.key }}
